security:
    password_hashers:
        App\Entity\User: auto

    providers:
        users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false

        api:
            pattern: ^/api/properties
            stateless: true
            provider: users
            jwt: ~

        login:
            pattern: ^/api/auth
            stateless: true
            json_login:
                check_path: /api/auth
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

    access_control:
        - { path: ^/api/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api/properties, roles: IS_AUTHENTICATED_FULLY }